syntax on

" Search
set ignorecase
set incsearch
set hlsearch

" Colorscheme (fallback if 'vim' doesn't exist)
try
  colorscheme vim
catch /^Vim\%((\a\+)\)\=:E185/
  colorscheme industry
endtry

" Line numbers
set number relativenumber

" Remap the system register clipboard for copy/paste
vnoremap <C-c> "+y
map <C-v> "+p

" Command-line completion menu
set wildmode=list:longest,list:full

" Highlight ONLY the current line number
set cursorline
if exists('&cursorlineopt')
  set cursorlineopt=number
endif

highlight CursorLineNr cterm=bold ctermfg=red guifg=#ff0000

" indentation
set tabstop=2
set shiftwidth=2
set expandtab
