background = rgba(191724ee)
surface = rgba(1f1d2eee)
overlay = rgba(26233aff)

text = rgba(e0def4ff)
muted = rgba(6e6a86ff)

accent = rgba(f2e9e1ee)
accent_secondary = rgba(d7827eee)

border = rgba(f2e9e1ee)
border_inactive = rgba(595959aa)

success = rgba(9ccfd8ff)
warning = rgba(f6c177ff)
error = rgba(eb6f92ff)

rounding = 12
border_width = 2
